package PanelesDespidos;

import Control.ControlSubsistemaDespidos;
import Controles.ControlFlujo;
import Excepciones.CorreoException;
import Exceptions.ObjetosNegocioException;
import dto.EmpleadoDTO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesús Ernesto López Ibarra (252663)
 */
public class ConfirmacionDespido extends javax.swing.JPanel {

    private static ConfirmacionDespido instance;
    private final ControlSubsistemaDespidos controlDespidos = new ControlSubsistemaDespidos();
    private EmpleadoDTO empleadoADespedir;
    private String razonDespido;

    /**
     * Creates new form BusquedaRFCNomina
     */
    public ConfirmacionDespido() {initComponents();}

    /**
     * Establece los datos del empleado a despedir y la razón del despido
     * que se mostrarán en el panel
     *
     * @param empleado El DTO del empleado seleccionado para el despido
     * @param razon    El motivo del despido
     */
    public void setDatosDespido(EmpleadoDTO empleado, String razon) {
        this.empleadoADespedir = empleado;
        this.razonDespido = razon;
        btnEstoySeguro.setSelected(false);
        btnNoEstoySeguro.setSelected(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEstoySeguro = new javax.swing.JCheckBox();
        btnNoEstoySeguro = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(17, 119, 202));

        btnVolver.setBackground(new java.awt.Color(44, 44, 44));
        btnVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(44, 44, 44));
        btnContinuar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 119, 202));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Esta usted seguro que desea despedirl@?");
        jPanel1.add(jLabel1);

        btnEstoySeguro.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnEstoySeguro.setText("Si estoy seguro");
        btnEstoySeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoySeguroActionPerformed(evt);
            }
        });

        btnNoEstoySeguro.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnNoEstoySeguro.setText("No estoy seguro");
        btnNoEstoySeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoEstoySeguroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNoEstoySeguro)
                            .addComponent(btnEstoySeguro))))
                .addGap(0, 437, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btnEstoySeguro)
                .addGap(60, 60, 60)
                .addComponent(btnNoEstoySeguro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setOpaque(false);
        btnVolver.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnContinuar.setBorderPainted(false);
        btnContinuar.setContentAreaFilled(false);
        btnContinuar.setOpaque(false);
        btnContinuar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento de clic del botón Volver
     * Regresa al panel de búsqueda de empleados para despedir
     *
     * @param evt El evento de acción que se generó
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlFlujo.mostrarBusquedaEmpleadoDespedir();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * Maneja el evento de clic del botón Continuar
     *
     * @param evt El evento de acción que se generó
     */
    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        if (btnEstoySeguro.isSelected()) {
            if (empleadoADespedir != null) {
                try {
                    controlDespidos.registrarDespido(empleadoADespedir, razonDespido);
                    JOptionPane.showMessageDialog(this, "Despido registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    ControlFlujo.mostrarMenuPrincipal();
                } catch (CorreoException ex) {
                    JOptionPane.showMessageDialog(this, "Error al enviar el correo de despido: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                } catch (ObjetosNegocioException ex) {
                    JOptionPane.showMessageDialog(this, "Error al registrar el despido: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se ha seleccionado un empleado para despedir.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (btnNoEstoySeguro.isSelected()) {
            JOptionPane.showMessageDialog(this, "Despido cancelado.", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
            ControlFlujo.mostrarMenuPrincipal();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, confirme si está seguro del despido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnEstoySeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoySeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstoySeguroActionPerformed

    private void btnNoEstoySeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoEstoySeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoEstoySeguroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JCheckBox btnEstoySeguro;
    private javax.swing.JCheckBox btnNoEstoySeguro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}