    package PanelesDespidos;

import Controles.ControlDespido;
import Controles.ControlFlujo;
import Excepciones.PresentacionException;
import dto.EmpleadoDTO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo Flores Leyva (252390)
 * @author José Alfredo Guzmán Moreno (252524)
 * @author Jesús Ernesto López Ibarra (252663)
 * @author José Luis Islas Molina (252574)
 * @author Benjamin Soto Coronado (253183)
 */
public class PrevisualizarEmpleadoDespedir extends javax.swing.JPanel {

    private EmpleadoDTO empleado;
    private final ControlDespido controlDespido = ControlDespido.getInstance();
    
    /**
     * Creates new form PrevisualisarEmpleado
     */
    public PrevisualizarEmpleadoDespedir() {initComponents();}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                int arc = 50; // Radio de redondeo

                // Dibujar fondo redondeado
                g2.setColor(getBackground());
                g2.fill(new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), arc, arc));

                g2.dispose();

                // Llamar a la implementación original para pintar los componentes hijos
                super.paintComponent(g);
            }

            @Override
            protected void paintBorder(Graphics g) {
                // No pintar el borde predeterminado
            }
        };
        ;
        staticNumEmpleado = new javax.swing.JLabel();
        lblnumEmpleado = new javax.swing.JLabel();
        lblnombreEmpleado = new javax.swing.JLabel();
        lblapellidoPaternoEmpleado = new javax.swing.JLabel();
        lblapellidoMaternoEmpleado = new javax.swing.JLabel();
        staticNombre = new javax.swing.JLabel();
        staticApellidoPat = new javax.swing.JLabel();
        staticApellidoMat = new javax.swing.JLabel();
        staticRFC = new javax.swing.JLabel();
        staticRazon = new javax.swing.JLabel();
        lblRFCEmpleado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtrazonEmpleado = new javax.swing.JTextField();

        setBackground(new java.awt.Color(17, 119, 202));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        btnConfirmar.setBackground(new java.awt.Color(44, 44, 44));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(44, 44, 44));
        btnVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(17, 119, 202));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1190, 508));
        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 508));
        jPanel1.setOpaque(false); // Hacer el panel transparente para que se vea el fondo redondeado
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Margen interno

        staticNumEmpleado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        staticNumEmpleado.setText("Num. Empleado:");

        lblnumEmpleado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblnumEmpleado.setText(".");

        lblnombreEmpleado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblnombreEmpleado.setText(".");

        lblapellidoPaternoEmpleado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblapellidoPaternoEmpleado.setText(".");

        lblapellidoMaternoEmpleado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblapellidoMaternoEmpleado.setText(".");

        staticNombre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        staticNombre.setText("Nombre:");

        staticApellidoPat.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        staticApellidoPat.setText("Apellido paterno:");

        staticApellidoMat.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        staticApellidoMat.setText("Apellido materno:");

        staticRFC.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        staticRFC.setText("RFC:");

        staticRazon.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        staticRazon.setText("Razón:");

        lblRFCEmpleado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblRFCEmpleado.setText(".");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel8.setText("Información del Empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staticRazon)
                            .addComponent(staticNombre)
                            .addComponent(staticApellidoPat)
                            .addComponent(staticApellidoMat)
                            .addComponent(staticRFC)
                            .addComponent(staticNumEmpleado))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblapellidoPaternoEmpleado)
                            .addComponent(lblapellidoMaternoEmpleado)
                            .addComponent(lblRFCEmpleado)
                            .addComponent(lblnumEmpleado)
                            .addComponent(lblnombreEmpleado)
                            .addComponent(txtrazonEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(staticRazon)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(staticNumEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staticNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(staticApellidoPat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staticApellidoMat)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(staticRFC)
                                    .addComponent(lblRFCEmpleado)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblnumEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblnombreEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblapellidoPaternoEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblapellidoMaternoEmpleado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtrazonEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirmar.setBorderPainted(false);
        btnConfirmar.setContentAreaFilled(false);
        btnConfirmar.setOpaque(false);
        btnConfirmar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setOpaque(false);
        btnVolver.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        //
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        ControlFlujo.mostrarBusquedaEmpleadoDespedir();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlFlujo.mostrarBusquedaEmpleadoDespedir();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String motivo = getMotivoDespido().trim();
        if (!motivo.isEmpty()) {
            ControlFlujo.mostrarPanelConfirmacionDespido(empleado, motivo);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el motivo del despido.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRFCEmpleado;
    private javax.swing.JLabel lblapellidoMaternoEmpleado;
    private javax.swing.JLabel lblapellidoPaternoEmpleado;
    private javax.swing.JLabel lblnombreEmpleado;
    private javax.swing.JLabel lblnumEmpleado;
    private javax.swing.JLabel staticApellidoMat;
    private javax.swing.JLabel staticApellidoPat;
    private javax.swing.JLabel staticNombre;
    private javax.swing.JLabel staticNumEmpleado;
    private javax.swing.JLabel staticRFC;
    private javax.swing.JLabel staticRazon;
    private javax.swing.JTextField txtrazonEmpleado;
    // End of variables declaration//GEN-END:variables

    public void setDatosEmpleado(EmpleadoDTO empleadoDTO) {
        this.empleado = empleadoDTO;
        // Actualizar las etiquetas con la información del empleado
        lblnombreEmpleado.setText(empleadoDTO.getNombre());
        lblapellidoPaternoEmpleado.setText(empleadoDTO.getApellidoPaterno());
        lblapellidoMaternoEmpleado.setText(empleadoDTO.getApellidoMaterno());
        lblRFCEmpleado.setText("RFC: " + empleadoDTO.getRfc());
    }
    
    public String getMotivoDespido() {
        return txtrazonEmpleado.getText();
    }

    public EmpleadoDTO getEmpleado() {
        return empleado;
    }
}