package PanelesReportes;

import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;

/**
 *
 * @author Leonardo Flores Leyva (252390)
 */
public class AnalisisInicialEInvestigacion extends javax.swing.JPanel {
    
    private final ConfirmacionMalaConducta confirmacionMalaConducta;
    
    /**
     * Creates new form PrevisualisarEmpleado
     */
    public AnalisisInicialEInvestigacion() {
        initComponents();
        confirmacionMalaConducta = new ConfirmacionMalaConducta((Frame) SwingUtilities.getWindowAncestor(this), true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLAnalisisInicial = new javax.swing.JLabel();
        jLInformacionCompleta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAOtrasEvidencias = new javax.swing.JTextArea();
        jLAccionesPrevias = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAOtrosAntecedentes = new javax.swing.JTextArea();
        jCLNoAntecedentes = new javax.swing.JCheckBox();
        jCLSiAntecedentes = new javax.swing.JCheckBox();
        jLOtrasEvidenciasRevisadas = new javax.swing.JLabel();
        jCLOtros = new javax.swing.JCheckBox();
        jCLNoInfoCompleta = new javax.swing.JCheckBox();
        jLInformacionCompleta2 = new javax.swing.JLabel();
        jLInformacionCompleta3 = new javax.swing.JLabel();
        jCLSiInfoCompleta1 = new javax.swing.JCheckBox();
        jCLEmpleadoInvolucrado = new javax.swing.JCheckBox();
        jCLTestigos = new javax.swing.JCheckBox();
        jCLSupervisor = new javax.swing.JCheckBox();
        jLEntrevistasRealizadas = new javax.swing.JLabel();
        jCLOtrasEvidencias = new javax.swing.JCheckBox();
        jCLDocumentosInternos = new javax.swing.JCheckBox();
        jCLCorreos = new javax.swing.JCheckBox();
        jCLGrabaciones = new javax.swing.JCheckBox();
        jLEvidenciasRevisadas = new javax.swing.JLabel();
        jLOtrasEntrevistasRealizadas1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAOtrasEntrevistas = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(17, 119, 202));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 628, 137, 55));
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setOpaque(false);
        btnCancelar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 628, 146, 55));
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setOpaque(false);
        btnSiguiente.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });

        jPanel2.setBackground(new java.awt.Color(17, 119, 202));
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 1280, -1));

        jLTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLTitulo.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Revision de reporte");
        jLTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jLTitulo.setOpaque(true);
        add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 44, -1, 55));

        jLAnalisisInicial.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLAnalisisInicial.setForeground(new java.awt.Color(255, 255, 255));
        jLAnalisisInicial.setText("Análisis Inicial:");
        add(jLAnalisisInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 334, 49));

        jLInformacionCompleta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLInformacionCompleta.setForeground(new java.awt.Color(0, 0, 0));
        jLInformacionCompleta.setText("Describa los antecedentes:");
        add(jLInformacionCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 400, 49));

        jTAOtrasEvidencias.setBackground(new java.awt.Color(255, 255, 255));
        jTAOtrasEvidencias.setColumns(20);
        jTAOtrasEvidencias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTAOtrasEvidencias.setForeground(new java.awt.Color(0, 0, 0));
        jTAOtrasEvidencias.setLineWrap(true);
        jTAOtrasEvidencias.setRows(5);
        jTAOtrasEvidencias.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTAOtrasEvidencias);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 330, 150));

        jLAccionesPrevias.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLAccionesPrevias.setForeground(new java.awt.Color(255, 255, 255));
        jLAccionesPrevias.setText("Investigación:");
        add(jLAccionesPrevias, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, 49));

        jTAOtrosAntecedentes.setBackground(new java.awt.Color(255, 255, 255));
        jTAOtrosAntecedentes.setColumns(20);
        jTAOtrosAntecedentes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTAOtrosAntecedentes.setForeground(new java.awt.Color(0, 0, 0));
        jTAOtrosAntecedentes.setLineWrap(true);
        jTAOtrosAntecedentes.setRows(5);
        jTAOtrosAntecedentes.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTAOtrosAntecedentes);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 400, 230));

        jCLNoAntecedentes.setBackground(new java.awt.Color(255, 255, 255));
        jCLNoAntecedentes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCLNoAntecedentes.setForeground(new java.awt.Color(0, 0, 0));
        jCLNoAntecedentes.setText("No");
        jCLNoAntecedentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLNoAntecedentes.setIconTextGap(10);
        jCLNoAntecedentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLNoAntecedentesActionPerformed(evt);
            }
        });
        add(jCLNoAntecedentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 80, 40));

        jCLSiAntecedentes.setBackground(new java.awt.Color(255, 255, 255));
        jCLSiAntecedentes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCLSiAntecedentes.setForeground(new java.awt.Color(0, 0, 0));
        jCLSiAntecedentes.setText("Sí");
        jCLSiAntecedentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLSiAntecedentes.setIconTextGap(10);
        add(jCLSiAntecedentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 40));

        jLOtrasEvidenciasRevisadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLOtrasEvidenciasRevisadas.setForeground(new java.awt.Color(0, 0, 0));
        jLOtrasEvidenciasRevisadas.setText("Describa las otras evidencias revisadas:");
        add(jLOtrasEvidenciasRevisadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 380, 30));

        jCLOtros.setBackground(new java.awt.Color(255, 255, 255));
        jCLOtros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCLOtros.setForeground(new java.awt.Color(0, 0, 0));
        jCLOtros.setText("Otros");
        jCLOtros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLOtros.setIconTextGap(10);
        jCLOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLOtrosActionPerformed(evt);
            }
        });
        add(jCLOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 310, 40));

        jCLNoInfoCompleta.setBackground(new java.awt.Color(255, 255, 255));
        jCLNoInfoCompleta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCLNoInfoCompleta.setForeground(new java.awt.Color(0, 0, 0));
        jCLNoInfoCompleta.setText("No");
        jCLNoInfoCompleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLNoInfoCompleta.setIconTextGap(10);
        jCLNoInfoCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLNoInfoCompletaActionPerformed(evt);
            }
        });
        add(jCLNoInfoCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 80, 40));

        jLInformacionCompleta2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLInformacionCompleta2.setForeground(new java.awt.Color(0, 0, 0));
        jLInformacionCompleta2.setText("¿Existen antecedentes previos del empleado*?");
        add(jLInformacionCompleta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 400, 49));

        jLInformacionCompleta3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLInformacionCompleta3.setForeground(new java.awt.Color(0, 0, 0));
        jLInformacionCompleta3.setText("¿El reporte tiene la información completa*?");
        add(jLInformacionCompleta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 390, 49));

        jCLSiInfoCompleta1.setBackground(new java.awt.Color(255, 255, 255));
        jCLSiInfoCompleta1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCLSiInfoCompleta1.setForeground(new java.awt.Color(0, 0, 0));
        jCLSiInfoCompleta1.setText("Sí");
        jCLSiInfoCompleta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLSiInfoCompleta1.setIconTextGap(10);
        add(jCLSiInfoCompleta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, 40));

        jCLEmpleadoInvolucrado.setBackground(new java.awt.Color(255, 255, 255));
        jCLEmpleadoInvolucrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCLEmpleadoInvolucrado.setForeground(new java.awt.Color(0, 0, 0));
        jCLEmpleadoInvolucrado.setText("Empleado involucrado");
        jCLEmpleadoInvolucrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLEmpleadoInvolucrado.setIconTextGap(10);
        jCLEmpleadoInvolucrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLEmpleadoInvolucradoActionPerformed(evt);
            }
        });
        add(jCLEmpleadoInvolucrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 310, 40));

        jCLTestigos.setBackground(new java.awt.Color(255, 255, 255));
        jCLTestigos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCLTestigos.setForeground(new java.awt.Color(0, 0, 0));
        jCLTestigos.setText("Testigo(s)");
        jCLTestigos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLTestigos.setIconTextGap(10);
        jCLTestigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLTestigosActionPerformed(evt);
            }
        });
        add(jCLTestigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 310, 40));

        jCLSupervisor.setBackground(new java.awt.Color(255, 255, 255));
        jCLSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCLSupervisor.setForeground(new java.awt.Color(0, 0, 0));
        jCLSupervisor.setText("Supervisor");
        jCLSupervisor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLSupervisor.setIconTextGap(10);
        jCLSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLSupervisorActionPerformed(evt);
            }
        });
        add(jCLSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 310, 40));

        jLEntrevistasRealizadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLEntrevistasRealizadas.setForeground(new java.awt.Color(0, 0, 0));
        jLEntrevistasRealizadas.setText("Entrevistas realizadas*:");
        add(jLEntrevistasRealizadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 200, 49));

        jCLOtrasEvidencias.setBackground(new java.awt.Color(255, 255, 255));
        jCLOtrasEvidencias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCLOtrasEvidencias.setForeground(new java.awt.Color(0, 0, 0));
        jCLOtrasEvidencias.setText("Otros");
        jCLOtrasEvidencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLOtrasEvidencias.setIconTextGap(10);
        jCLOtrasEvidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLOtrasEvidenciasActionPerformed(evt);
            }
        });
        add(jCLOtrasEvidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, 310, 40));

        jCLDocumentosInternos.setBackground(new java.awt.Color(255, 255, 255));
        jCLDocumentosInternos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCLDocumentosInternos.setForeground(new java.awt.Color(0, 0, 0));
        jCLDocumentosInternos.setText("Documentos internos");
        jCLDocumentosInternos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLDocumentosInternos.setIconTextGap(10);
        jCLDocumentosInternos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLDocumentosInternosActionPerformed(evt);
            }
        });
        add(jCLDocumentosInternos, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 310, 40));

        jCLCorreos.setBackground(new java.awt.Color(255, 255, 255));
        jCLCorreos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCLCorreos.setForeground(new java.awt.Color(0, 0, 0));
        jCLCorreos.setText("Correos electrónicos");
        jCLCorreos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLCorreos.setIconTextGap(10);
        jCLCorreos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLCorreosActionPerformed(evt);
            }
        });
        add(jCLCorreos, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 310, 40));

        jCLGrabaciones.setBackground(new java.awt.Color(255, 255, 255));
        jCLGrabaciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCLGrabaciones.setForeground(new java.awt.Color(0, 0, 0));
        jCLGrabaciones.setText("Grabaciones");
        jCLGrabaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCLGrabaciones.setIconTextGap(10);
        jCLGrabaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLGrabacionesActionPerformed(evt);
            }
        });
        add(jCLGrabaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 310, 40));

        jLEvidenciasRevisadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLEvidenciasRevisadas.setForeground(new java.awt.Color(0, 0, 0));
        jLEvidenciasRevisadas.setText("Entrevistas realizadas*:");
        add(jLEvidenciasRevisadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 200, 49));

        jLOtrasEntrevistasRealizadas1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLOtrasEntrevistasRealizadas1.setForeground(new java.awt.Color(0, 0, 0));
        jLOtrasEntrevistasRealizadas1.setText("Describa las otras entrevistas realizadas:");
        add(jLOtrasEntrevistasRealizadas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 380, 30));

        jTAOtrasEntrevistas.setBackground(new java.awt.Color(255, 255, 255));
        jTAOtrasEntrevistas.setColumns(20);
        jTAOtrasEntrevistas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTAOtrasEntrevistas.setForeground(new java.awt.Color(0, 0, 0));
        jTAOtrasEntrevistas.setLineWrap(true);
        jTAOtrasEntrevistas.setRows(5);
        jTAOtrasEntrevistas.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTAOtrasEntrevistas);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 350, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jCLNoAntecedentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLNoAntecedentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLNoAntecedentesActionPerformed

    private void jCLNoInfoCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLNoInfoCompletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLNoInfoCompletaActionPerformed

    private void jCLOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLOtrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLOtrosActionPerformed

    private void jCLEmpleadoInvolucradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLEmpleadoInvolucradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLEmpleadoInvolucradoActionPerformed

    private void jCLTestigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLTestigosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLTestigosActionPerformed

    private void jCLSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLSupervisorActionPerformed

    private void jCLOtrasEvidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLOtrasEvidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLOtrasEvidenciasActionPerformed

    private void jCLDocumentosInternosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLDocumentosInternosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLDocumentosInternosActionPerformed

    private void jCLCorreosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLCorreosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLCorreosActionPerformed

    private void jCLGrabacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLGrabacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCLGrabacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBox jCLCorreos;
    private javax.swing.JCheckBox jCLDocumentosInternos;
    private javax.swing.JCheckBox jCLEmpleadoInvolucrado;
    private javax.swing.JCheckBox jCLGrabaciones;
    private javax.swing.JCheckBox jCLNoAntecedentes;
    private javax.swing.JCheckBox jCLNoInfoCompleta;
    private javax.swing.JCheckBox jCLOtrasEvidencias;
    private javax.swing.JCheckBox jCLOtros;
    private javax.swing.JCheckBox jCLSiAntecedentes;
    private javax.swing.JCheckBox jCLSiInfoCompleta1;
    private javax.swing.JCheckBox jCLSupervisor;
    private javax.swing.JCheckBox jCLTestigos;
    private javax.swing.JLabel jLAccionesPrevias;
    private javax.swing.JLabel jLAnalisisInicial;
    private javax.swing.JLabel jLEntrevistasRealizadas;
    private javax.swing.JLabel jLEvidenciasRevisadas;
    private javax.swing.JLabel jLInformacionCompleta;
    private javax.swing.JLabel jLInformacionCompleta2;
    private javax.swing.JLabel jLInformacionCompleta3;
    private javax.swing.JLabel jLOtrasEntrevistasRealizadas1;
    private javax.swing.JLabel jLOtrasEvidenciasRevisadas;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAOtrasEntrevistas;
    private javax.swing.JTextArea jTAOtrasEvidencias;
    private javax.swing.JTextArea jTAOtrosAntecedentes;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancelar() {return btnCancelar;}

    public void setBtnCancelar(JButton btnCancelar) {this.btnCancelar = btnCancelar;}

    public JButton getBtnGenerar() {return btnSiguiente;}

    public void setBtnGenerar(JButton btnGenerar) {this.btnSiguiente = btnGenerar;}

}