package PanelesReportes;

import Controles.ControlFlujo;
import OptionPane.OptionPane;
import dto.ReporteMalaConductaDTO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 * Panel para la muestra de los datos del reporte de mala
 * conducta a revisar.
 * @author Leonardo Flores Leyva (252390)
 */
public class DatosGenerales extends javax.swing.JPanel {
    // Reporte de mala conducta a mostrar.
    private ReporteMalaConductaDTO reporteMalaConducta = new ReporteMalaConductaDTO();
    // Modelo de la lista de tetigos
    private final DefaultListModel modeloLista = new DefaultListModel();
    /**
     * Creates new form PrevisualisarEmpleado
     */
    public DatosGenerales() {
        initComponents();
        jListTestigos.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLugarIncidente = new javax.swing.JLabel();
        jTFLugarIncidente = new javax.swing.JTextField();
        jLDescripcionDetallada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcionDetallada = new javax.swing.JTextArea();
        jLNombreEmpleado = new javax.swing.JLabel();
        jTFNombreEmpleado = new javax.swing.JTextField();
        jLPuesto = new javax.swing.JLabel();
        jTFPuesto = new javax.swing.JTextField();
        jTFDepartamento = new javax.swing.JTextField();
        jLDepartamento = new javax.swing.JLabel();
        jTFechaHoraIncidente = new javax.swing.JTextField();
        jLFechaHoraIncidente = new javax.swing.JLabel();
        jTFReportadoPor = new javax.swing.JTextField();
        jLReportadoPor = new javax.swing.JLabel();
        jTFCargoReportante = new javax.swing.JTextField();
        jLCargoReportante = new javax.swing.JLabel();
        jLTestigos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTestigos = new javax.swing.JList<>();
        jLImpactoIncidente = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAccionesPrevias = new javax.swing.JTextArea();
        jLAccionesPrevias = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAImpactoIncidente = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(17, 119, 202));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnIniciar.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar");
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(17, 119, 202));

        jLTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLTitulo.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Datos generales:");
        jLTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jLTitulo.setOpaque(true);

        jLugarIncidente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLugarIncidente.setForeground(new java.awt.Color(0, 0, 0));
        jLugarIncidente.setText("Lugar del incidente*:");

        jTFLugarIncidente.setEditable(false);
        jTFLugarIncidente.setBackground(new java.awt.Color(255, 255, 255));
        jTFLugarIncidente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTFLugarIncidente.setForeground(new java.awt.Color(0, 0, 0));
        jTFLugarIncidente.setBorder(null);
        jTFLugarIncidente.setMargin(new java.awt.Insets(2, 15, 2, 6));

        jLDescripcionDetallada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLDescripcionDetallada.setForeground(new java.awt.Color(0, 0, 0));
        jLDescripcionDetallada.setText("Descripción detallada*:");

        jTADescripcionDetallada.setEditable(false);
        jTADescripcionDetallada.setBackground(new java.awt.Color(255, 255, 255));
        jTADescripcionDetallada.setColumns(20);
        jTADescripcionDetallada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTADescripcionDetallada.setForeground(new java.awt.Color(0, 0, 0));
        jTADescripcionDetallada.setLineWrap(true);
        jTADescripcionDetallada.setRows(5);
        jTADescripcionDetallada.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTADescripcionDetallada);

        jLNombreEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLNombreEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        jLNombreEmpleado.setText("Nombre del empleado:");

        jTFNombreEmpleado.setEditable(false);
        jTFNombreEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jTFNombreEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTFNombreEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        jTFNombreEmpleado.setBorder(null);
        jTFNombreEmpleado.setMargin(new java.awt.Insets(2, 15, 2, 6));

        jLPuesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLPuesto.setForeground(new java.awt.Color(0, 0, 0));
        jLPuesto.setText("Puesto:");

        jTFPuesto.setEditable(false);
        jTFPuesto.setBackground(new java.awt.Color(255, 255, 255));
        jTFPuesto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTFPuesto.setForeground(new java.awt.Color(0, 0, 0));
        jTFPuesto.setBorder(null);
        jTFPuesto.setMargin(new java.awt.Insets(2, 15, 2, 6));

        jTFDepartamento.setEditable(false);
        jTFDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        jTFDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTFDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        jTFDepartamento.setBorder(null);
        jTFDepartamento.setMargin(new java.awt.Insets(2, 15, 2, 6));

        jLDepartamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        jLDepartamento.setText("Departamento:");

        jTFechaHoraIncidente.setEditable(false);
        jTFechaHoraIncidente.setBackground(new java.awt.Color(255, 255, 255));
        jTFechaHoraIncidente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTFechaHoraIncidente.setForeground(new java.awt.Color(0, 0, 0));
        jTFechaHoraIncidente.setBorder(null);
        jTFechaHoraIncidente.setMargin(new java.awt.Insets(2, 15, 2, 6));

        jLFechaHoraIncidente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLFechaHoraIncidente.setForeground(new java.awt.Color(0, 0, 0));
        jLFechaHoraIncidente.setText("Fecha y hora de incidente:");

        jTFReportadoPor.setEditable(false);
        jTFReportadoPor.setBackground(new java.awt.Color(255, 255, 255));
        jTFReportadoPor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTFReportadoPor.setForeground(new java.awt.Color(0, 0, 0));
        jTFReportadoPor.setBorder(null);
        jTFReportadoPor.setMargin(new java.awt.Insets(2, 15, 2, 6));

        jLReportadoPor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLReportadoPor.setForeground(new java.awt.Color(0, 0, 0));
        jLReportadoPor.setText("Reportado por:");

        jTFCargoReportante.setEditable(false);
        jTFCargoReportante.setBackground(new java.awt.Color(255, 255, 255));
        jTFCargoReportante.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTFCargoReportante.setForeground(new java.awt.Color(0, 0, 0));
        jTFCargoReportante.setBorder(null);
        jTFCargoReportante.setMargin(new java.awt.Insets(2, 15, 2, 6));

        jLCargoReportante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLCargoReportante.setForeground(new java.awt.Color(0, 0, 0));
        jLCargoReportante.setText("Cargo del reportante:");

        jLTestigos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTestigos.setForeground(new java.awt.Color(0, 0, 0));
        jLTestigos.setText("Testigos:");

        jListTestigos.setBackground(new java.awt.Color(255, 255, 255));
        jListTestigos.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jListTestigos);

        jLImpactoIncidente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLImpactoIncidente.setForeground(new java.awt.Color(0, 0, 0));
        jLImpactoIncidente.setText("Impacto del incidente:");

        jTAccionesPrevias.setEditable(false);
        jTAccionesPrevias.setBackground(new java.awt.Color(255, 255, 255));
        jTAccionesPrevias.setColumns(20);
        jTAccionesPrevias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTAccionesPrevias.setForeground(new java.awt.Color(0, 0, 0));
        jTAccionesPrevias.setLineWrap(true);
        jTAccionesPrevias.setRows(5);
        jTAccionesPrevias.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTAccionesPrevias);

        jLAccionesPrevias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLAccionesPrevias.setForeground(new java.awt.Color(0, 0, 0));
        jLAccionesPrevias.setText("Acciones previas:");

        jTAImpactoIncidente.setEditable(false);
        jTAImpactoIncidente.setBackground(new java.awt.Color(255, 255, 255));
        jTAImpactoIncidente.setColumns(20);
        jTAImpactoIncidente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTAImpactoIncidente.setForeground(new java.awt.Color(0, 0, 0));
        jTAImpactoIncidente.setLineWrap(true);
        jTAImpactoIncidente.setRows(5);
        jTAImpactoIncidente.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTAImpactoIncidente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLugarIncidente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFLugarIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLNombreEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLFechaHoraIncidente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFechaHoraIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLReportadoPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFReportadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLCargoReportante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCargoReportante, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTestigos))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAccionesPrevias)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLDescripcionDetallada))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLImpactoIncidente))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFechaHoraIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFechaHoraIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLReportadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFReportadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCargoReportante, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCargoReportante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFLugarIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLugarIncidente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTestigos)
                            .addComponent(jLAccionesPrevias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDescripcionDetallada)
                            .addComponent(jLImpactoIncidente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setOpaque(false);
        btnCancelar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnIniciar.setBorderPainted(false);
        btnIniciar.setContentAreaFilled(false);
        btnIniciar.setOpaque(false);
        btnIniciar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botón Iniciar. Transfiere el reporte de mala conducta a la
     * pantalla de Análisis Inicial e Investigación.
     * @param evt Click.
     */
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
    }//GEN-LAST:event_btnIniciarActionPerformed
    /**
     * Botón Cancelar. Regresa al Submenú de Reportes de Mala Conducta.
     * @param evt Click.
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int confirmacion = OptionPane.showConfirmDialog(this, "¿Seguro que desea cancelar la operación?", "Confirmación de cancelación");
        if(confirmacion == JOptionPane.YES_OPTION)
            ControlFlujo.mostrarSubmenuReportes();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Reemplaza el reporte de este panel por
     * el reporte recibido.
     * @param reporte Reporte en transferencia.
     */
    public void cargarReporte(ReporteMalaConductaDTO reporte){
        if(reporte != null){
            reporteMalaConducta = reporte;
            /*
                Las siguientes validaciones son únicamente para garantizar que el sistema no truene, en caso de que algún dato del reporte
                sea null (lo cual no debería pasar, ya que se debió haber obtenido un reportye completo). Además, hay algunos campos
                opcionales, como las acciones previas, que no se persisten en la BD si no se ingresó su información.
            */
            
            // Nombre del empleado reportado.
            if(reporteMalaConducta.getEmpleadoReportado() != null && reporteMalaConducta.getEmpleadoReportado().getNombre() != null)
                jTFNombreEmpleado.setText(reporteMalaConducta.getEmpleadoReportado().getNombre());
            // Departamento del empleado reportado.
            if(reporteMalaConducta.getEmpleadoReportado() != null && reporteMalaConducta.getEmpleadoReportado().getDepartamento() != null)
                jTFDepartamento.setText(reporteMalaConducta.getEmpleadoReportado().getDepartamento());
            // Puesto del empleado reportado.
            if(reporteMalaConducta.getEmpleadoReportado() != null && reporteMalaConducta.getEmpleadoReportado().getPuesto() != null)
                jTFPuesto.setText(reporteMalaConducta.getEmpleadoReportado().getPuesto());
            // Fecha y hora del incidente.
            if(reporteMalaConducta.getFechaHoraIncidente() != null){
                String fechaHoraIncidente = String.format(
                        "%d/%d/%d %d:%d:%d", 
                        reporteMalaConducta.getFechaHoraIncidente().getDayOfMonth(),
                        reporteMalaConducta.getFechaHoraIncidente().getMonthValue(),
                        reporteMalaConducta.getFechaHoraIncidente().getYear(),
                        reporteMalaConducta.getFechaHoraIncidente().getHour(),
                        reporteMalaConducta.getFechaHoraIncidente().getMinute(),
                        reporteMalaConducta.getFechaHoraIncidente().getSecond()
                );
                jTFechaHoraIncidente.setText(fechaHoraIncidente);
            }
            // Nombre del empleado reportante.
            if(reporteMalaConducta.getEmpleadoReportante() != null && reporteMalaConducta.getEmpleadoReportante().getNombre() != null)
                jTFReportadoPor.setText(reporteMalaConducta.getEmpleadoReportante().getNombre());
            // Cargo del empleado reportante.
            if(reporteMalaConducta.getEmpleadoReportante() != null && reporteMalaConducta.getEmpleadoReportante().getPuesto() != null)
                jTFCargoReportante.setText(reporteMalaConducta.getEmpleadoReportante().getPuesto());
            // Lugar del incidente.
            if(reporteMalaConducta.getLugarIncidente() != null)
                jTFLugarIncidente.setText(reporteMalaConducta.getLugarIncidente());
            // Testigos (si es que hubieron).
            if(reporteMalaConducta.getTestigos() != null && !reporteMalaConducta.getTestigos().isEmpty()){
                for (int i = 0; i < reporteMalaConducta.getTestigos().size(); i++) {
                    String testigo = reporteMalaConducta.getTestigos().get(i);
                    modeloLista.add(i, testigo);
                }
            }
            // Impacto del incidente.
            if(reporteMalaConducta.getImpactoIncidente() != null)
                jTAImpactoIncidente.setText(reporteMalaConducta.getImpactoIncidente());
            // Acciones previas del empleado reportado (si es que se ingresó tal información, ya que es opcional).
            if(reporteMalaConducta.getAccionesPrevias() != null)
                jTAccionesPrevias.setText(reporteMalaConducta.getAccionesPrevias());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLAccionesPrevias;
    private javax.swing.JLabel jLCargoReportante;
    private javax.swing.JLabel jLDepartamento;
    private javax.swing.JLabel jLDescripcionDetallada;
    private javax.swing.JLabel jLFechaHoraIncidente;
    private javax.swing.JLabel jLImpactoIncidente;
    private javax.swing.JLabel jLNombreEmpleado;
    private javax.swing.JLabel jLPuesto;
    private javax.swing.JLabel jLReportadoPor;
    private javax.swing.JLabel jLTestigos;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JList<String> jListTestigos;
    private javax.swing.JLabel jLugarIncidente;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTADescripcionDetallada;
    private javax.swing.JTextArea jTAImpactoIncidente;
    private javax.swing.JTextArea jTAccionesPrevias;
    private javax.swing.JTextField jTFCargoReportante;
    private javax.swing.JTextField jTFDepartamento;
    private javax.swing.JTextField jTFLugarIncidente;
    private javax.swing.JTextField jTFNombreEmpleado;
    private javax.swing.JTextField jTFPuesto;
    private javax.swing.JTextField jTFReportadoPor;
    private javax.swing.JTextField jTFechaHoraIncidente;
    // End of variables declaration//GEN-END:variables
}