package PanelesReportes;

import Controles.ControlCampos;
import Controles.ControlFlujo;
import Controles.ControlReportes;
import Excepciones.PresentacionException;
import OptionPane.OptionPane;
import dto.EmpleadoDTO;
import dto.ReporteMalaConductaDTO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.swing.JComponent;

/**
 * Panel para el ingreso del RFC del empleado reportante
 * y reportado, y la fecha y hora del incidente.
 * @author Leonardo Flores Leyva (252390)
 */
public class RegistroDatosGenerales extends javax.swing.JPanel {

    /**
     * Creates new form PrevisualisarEmpleado
     */
    public RegistroDatosGenerales() {
        initComponents();
        ControlCampos.limiteCaracteresCampoTexto(jTRFCReportado, 13);
        ControlCampos.limiteCaracteresCampoTexto(jTRFCReportante, 13);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLDatosGenerales = new javax.swing.JLabel();
        jLRFCReportado = new javax.swing.JLabel();
        jTRFCReportado = new javax.swing.JTextField();
        jTRFCReportante = new javax.swing.JTextField();
        jLRFCReportante = new javax.swing.JLabel();
        jLFechaIncidente = new javax.swing.JLabel();
        jDPFechaIncidente = new raven.datetime.DatePicker();
        jLHoraIncidente = new javax.swing.JLabel();
        jTPHoraIncidente = new raven.datetime.TimePicker();

        setBackground(new java.awt.Color(17, 119, 202));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(17, 119, 202));

        jLTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLTitulo.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Reportes de mala conducta de empleados");
        jLTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jLTitulo.setOpaque(true);

        jLDatosGenerales.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLDatosGenerales.setForeground(new java.awt.Color(255, 255, 255));
        jLDatosGenerales.setText("Datos Generales:");

        jLRFCReportado.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLRFCReportado.setForeground(new java.awt.Color(0, 0, 0));
        jLRFCReportado.setText("RFC del empleado reportado*:");

        jTRFCReportado.setBackground(new java.awt.Color(255, 255, 255));
        jTRFCReportado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTRFCReportado.setForeground(new java.awt.Color(0, 0, 0));
        jTRFCReportado.setBorder(null);
        jTRFCReportado.setMargin(new java.awt.Insets(2, 15, 2, 6));

        jTRFCReportante.setBackground(new java.awt.Color(255, 255, 255));
        jTRFCReportante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTRFCReportante.setForeground(new java.awt.Color(0, 0, 0));
        jTRFCReportante.setBorder(null);
        jTRFCReportante.setMargin(new java.awt.Insets(2, 15, 2, 6));

        jLRFCReportante.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLRFCReportante.setForeground(new java.awt.Color(0, 0, 0));
        jLRFCReportante.setText("Reportado por (RFC)*:");

        jLFechaIncidente.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLFechaIncidente.setForeground(new java.awt.Color(0, 0, 0));
        jLFechaIncidente.setText("Fecha de incidente*:");

        jDPFechaIncidente.setBackground(new java.awt.Color(0, 0, 0));
        jDPFechaIncidente.setForeground(new java.awt.Color(255, 255, 255));

        jLHoraIncidente.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLHoraIncidente.setForeground(new java.awt.Color(0, 0, 0));
        jLHoraIncidente.setText("Hora de incidente*:");

        jTPHoraIncidente.setBackground(new java.awt.Color(0, 0, 0));
        jTPHoraIncidente.setForeground(new java.awt.Color(255, 255, 255));
        jTPHoraIncidente.setColor(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTitulo)
                    .addComponent(jLDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTRFCReportado, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLRFCReportado, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTRFCReportante, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLRFCReportante, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFechaIncidente)
                            .addComponent(jDPFechaIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPHoraIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLHoraIncidente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRFCReportado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFechaIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLHoraIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTRFCReportado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLRFCReportante, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTRFCReportante, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDPFechaIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTPHoraIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setOpaque(false);
        btnCancelar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setOpaque(false);
        btnSiguiente.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        ControlReportes controlReportes = ControlReportes.getInstance();
        try {
            
            EmpleadoDTO empleadoReportado = new EmpleadoDTO();
            empleadoReportado.setRfc(jTRFCReportado.getText());
            empleadoReportado = controlReportes.obtenerEmpleado(empleadoReportado);
            
            EmpleadoDTO empleadoReportante = new EmpleadoDTO();
            empleadoReportante.setRfc(jTRFCReportante.getText());
            empleadoReportante = controlReportes.obtenerEmpleado(empleadoReportado);
            
            LocalDate fechaIncidente = jDPFechaIncidente.getSelectedDate();
            LocalTime horaIncidente = jTPHoraIncidente.getSelectedTime();
            
            ReporteMalaConductaDTO reporteMalaConducta = new ReporteMalaConductaDTO();
            reporteMalaConducta.setEmpleadoReportado(empleadoReportado);
            reporteMalaConducta.setEmpleadoReportante(empleadoReportante);
            reporteMalaConducta.setFechaHoraIncidente(LocalDateTime.of(fechaIncidente, horaIncidente));
            
            ControlFlujo.mostrarDescripcionIncidente(reporteMalaConducta);
            
        } catch (PresentacionException e) {OptionPane.showErrorMessage(this, e.getMessage(), "ERROR");}
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        jTRFCReportado.setText("");
        jTRFCReportante.setText("");
        jDPFechaIncidente.setSelectedDate(LocalDate.now());
        jTPHoraIncidente.setSelectedTime(LocalTime.now());
        ControlFlujo.mostrarSubmenuReportes();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private raven.datetime.DatePicker jDPFechaIncidente;
    private javax.swing.JLabel jLDatosGenerales;
    private javax.swing.JLabel jLFechaIncidente;
    private javax.swing.JLabel jLHoraIncidente;
    private javax.swing.JLabel jLRFCReportado;
    private javax.swing.JLabel jLRFCReportante;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel2;
    private raven.datetime.TimePicker jTPHoraIncidente;
    private javax.swing.JTextField jTRFCReportado;
    private javax.swing.JTextField jTRFCReportante;
    // End of variables declaration//GEN-END:variables
}