package PanelesExpedientes;

import Controles.ControlFlujo;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;

/**
 *
 * @author José Alfredo Guzman Moreno (252524)
 */
public class SubmenuExpedientes extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarAsistencia
     */
    public SubmenuExpedientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        btnConsultarExpediente = new javax.swing.JButton();
        btnModificarExpediente = new javax.swing.JButton();

        setBackground(new java.awt.Color(17, 119, 202));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        btnVolver.setBackground(new java.awt.Color(51, 51, 51));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnConsultarExpediente.setBackground(new java.awt.Color(44, 44, 44));
        btnConsultarExpediente.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnConsultarExpediente.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegistrarCandidato/EvaluarCandidato.png"))); // NOI18N
        btnConsultarExpediente.setText("<html>Consultar<br>Expediente</html>");
        btnConsultarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarExpedienteActionPerformed(evt);
            }
        });

        btnModificarExpediente.setBackground(new java.awt.Color(44, 44, 44));
        btnModificarExpediente.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnModificarExpediente.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegistrarCandidato/EvaluarCandidato.png"))); // NOI18N
        btnModificarExpediente.setText("<html>Modificar<br>Expediente</html>");
        btnModificarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarExpedienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConsultarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(btnModificarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        btnConsultarExpediente.setBorderPainted(false);
        btnConsultarExpediente.setContentAreaFilled(false);
        btnConsultarExpediente.setOpaque(false);
        btnConsultarExpediente.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnModificarExpediente.setBorderPainted(false);
        btnModificarExpediente.setContentAreaFilled(false);
        btnModificarExpediente.setOpaque(false);
        btnModificarExpediente.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlFlujo.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConsultarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarExpedienteActionPerformed
        ControlFlujo.mostrarExpedienteEmpleado();
    }//GEN-LAST:event_btnConsultarExpedienteActionPerformed

    private void btnModificarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarExpedienteActionPerformed
        ControlFlujo.mostrarModificarExpediente();
    }//GEN-LAST:event_btnModificarExpedienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarExpediente;
    private javax.swing.JButton btnModificarExpediente;
    private javax.swing.JButton btnVolver;
    // End of variables declaration//GEN-END:variables
}
