/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import Controles.ControlFlujo;
import Paneles.BusquedaRFCNomina;
import Paneles.MenuPrincipal;
import Paneles.PrevisualizarEmpleado;
import Paneles.PrevisualizarNomina;
import java.awt.CardLayout;

/**
 *
 * @author INSPIRON
 */
public class CarcasaPaneles extends javax.swing.JFrame {

    
    private static CarcasaPaneles instance;
    
    private MenuPrincipal menuPrincipal;
    private BusquedaRFCNomina busquedaRFCNomina;
    private PrevisualizarEmpleado previsualisarEmpleado;
    private PrevisualizarNomina previsualizarNomina;
    
    /**
     * Creates new form CarcasaPaneles
     */
    private CarcasaPaneles() {
        initComponents();
        cargarPaneles();
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    private void cargarPaneles() {
        menuPrincipal = MenuPrincipal.getInstance();
        busquedaRFCNomina = BusquedaRFCNomina.getInstance();
        previsualisarEmpleado = PrevisualizarEmpleado.getInstance();
        previsualizarNomina = PrevisualizarNomina.getInstance();
        contenedor.add(menuPrincipal, "menuPrincipal");
        contenedor.add(busquedaRFCNomina, "busquedaRFCNomina");
        contenedor.add(previsualisarEmpleado, "previsualisarEmpleado");
        contenedor.add(previsualizarNomina,"previsualizarNomina");
    }
    public static CarcasaPaneles getInstance() {
        if (instance == null) {
            instance = new CarcasaPaneles();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        contenedor.setMaximumSize(new java.awt.Dimension(1280, 720));
        contenedor.setMinimumSize(new java.awt.Dimension(1280, 720));
        contenedor.setPreferredSize(new java.awt.Dimension(1280, 720));
        contenedor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarcasaPaneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarcasaPaneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarcasaPaneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarcasaPaneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarcasaPaneles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    // End of variables declaration//GEN-END:variables
}
