/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesRegistroEmpleado;

import Controles.ControlFlujo;
import Controles.ControlFlujoRegistro;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;

/**
 *
 * @author skyro
 */
public class MenuContrataciones extends javax.swing.JPanel {

    /**
     * Creates new form MenuContrataciones
     */
    public MenuContrataciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAñadirCandidato = new javax.swing.JButton();
        btnEvaluarCandidato = new javax.swing.JButton();
        btnGenerarContrato = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 119, 202));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        btnAñadirCandidato.setBackground(new java.awt.Color(44, 44, 44));
        btnAñadirCandidato.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnAñadirCandidato.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegistrarCandidato/AgregarUsuario.png"))); // NOI18N
        btnAñadirCandidato.setText("<html>Añadir<br>Candidato</html>");
        btnAñadirCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirCandidatoActionPerformed(evt);
            }
        });

        btnEvaluarCandidato.setBackground(new java.awt.Color(44, 44, 44));
        btnEvaluarCandidato.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnEvaluarCandidato.setForeground(new java.awt.Color(255, 255, 255));
        btnEvaluarCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegistrarCandidato/EvaluarCandidato.png"))); // NOI18N
        btnEvaluarCandidato.setText("<html>Evaluar<br>Candidato</html>");
        btnEvaluarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarCandidatoActionPerformed(evt);
            }
        });

        btnGenerarContrato.setBackground(new java.awt.Color(44, 44, 44));
        btnGenerarContrato.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnGenerarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegistrarCandidato/GenerarContrato.png"))); // NOI18N
        btnGenerarContrato.setText("<html>Generar<br>Contrato</html>");
        btnGenerarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarContratoActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(44, 44, 44));
        btnVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 119, 202));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setText("Contrataciones");
        jPanel1.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnAñadirCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEvaluarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(514, 514, 514))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadirCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvaluarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        btnAñadirCandidato.setBorderPainted(false);
        btnAñadirCandidato.setContentAreaFilled(false);
        btnAñadirCandidato.setOpaque(false);
        btnAñadirCandidato.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnEvaluarCandidato.setBorderPainted(false);
        btnEvaluarCandidato.setContentAreaFilled(false);
        btnEvaluarCandidato.setOpaque(false);
        btnEvaluarCandidato.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnGenerarContrato.setBorderPainted(false);
        btnGenerarContrato.setContentAreaFilled(false);
        btnGenerarContrato.setOpaque(false);
        btnGenerarContrato.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setOpaque(false);
        btnVolver.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 50, 50);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirCandidatoActionPerformed
        ControlFlujoRegistro.mostrarRegistrarCandidato();
    }//GEN-LAST:event_btnAñadirCandidatoActionPerformed

    private void btnEvaluarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarCandidatoActionPerformed
        ControlFlujoRegistro.mostrarSeleccionarCandidatoEvaluacion();
    }//GEN-LAST:event_btnEvaluarCandidatoActionPerformed

    private void btnGenerarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarContratoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlFlujo.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirCandidato;
    private javax.swing.JButton btnEvaluarCandidato;
    private javax.swing.JButton btnGenerarContrato;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
