/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesRegistrarAsistencia;

import Controles.ControlAsistencia;
import Controles.ControlFlujo;
import Excepciones.PresentacionException;
import OptionPane.OptionPane;
import dto.EmpleadoDTO;
import dto.HorarioLaboralDTO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicTextFieldUI;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author INSPIRON
 */
public class RegistrarSalida extends javax.swing.JPanel {
    private EmpleadoDTO empleadoEncontrado;
    private final ControlAsistencia control;
    /**
     * Creates new form SubmenuRegistrarAsistencia
     */
    public RegistrarSalida() {
        initComponents();
        control = ControlAsistencia.getInstance();
        ocultarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtRfcRegistrarSalida = new javax.swing.JTextField();
        btnBuscarEmpleado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlblNombreEmpleado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblFechaActual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblHoraDeSalidaEsperada = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlblHoraDeSalida = new javax.swing.JLabel();
        btnRegistrarSalida = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(17, 119, 202));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingresar el RFC del empleado:");

        txtRfcRegistrarSalida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtRfcRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcRegistrarSalidaActionPerformed(evt);
            }
        });

        btnBuscarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarEmpleado.setText("Buscar Empleado");
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre del empleado:");

        jlblNombreEmpleado.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlblNombreEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jlblNombreEmpleado.setText("nombre");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha Actual: ");

        jlblFechaActual.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlblFechaActual.setForeground(new java.awt.Color(255, 255, 255));
        jlblFechaActual.setText("fecha actual del sistema");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hora de salida esperada:");

        jlblHoraDeSalidaEsperada.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlblHoraDeSalidaEsperada.setForeground(new java.awt.Color(255, 255, 255));
        jlblHoraDeSalidaEsperada.setText("Hora de salida que aparece en su horario");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hora salida:");

        jlblHoraDeSalida.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlblHoraDeSalida.setForeground(new java.awt.Color(255, 255, 255));
        jlblHoraDeSalida.setText("Hora actual del sistema");

        btnRegistrarSalida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarSalida.setText("Registrar Salida");
        btnRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSalidaActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtRfcRegistrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblFechaActual)
                            .addComponent(jlblNombreEmpleado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblHoraDeSalidaEsperada)
                            .addComponent(jlblHoraDeSalida))))
                .addContainerGap(407, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnRegistrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRfcRegistrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblNombreEmpleado))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlblFechaActual))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlblHoraDeSalidaEsperada))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlblHoraDeSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        txtRfcRegistrarSalida.setToolTipText("Ingrese el RFC.");
        txtRfcRegistrarSalida.setHorizontalAlignment(SwingConstants.CENTER);
        txtRfcRegistrarSalida.setOpaque(false); // Hace que el fondo predeterminado no se pinte
        txtRfcRegistrarSalida.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)); // Margen interno para el texto
        txtRfcRegistrarSalida.setUI(new BasicTextFieldUI() {
            @Override
            protected void paintSafely(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                int arc = 50; // Radio de redondeo

                // Dibujar fondo redondeado
                g2.setColor(txtRfcRegistrarSalida.getBackground());
                g2.fill(new RoundRectangle2D.Float(0, 0, txtRfcRegistrarSalida.getWidth(), txtRfcRegistrarSalida.getHeight(), arc, arc));

                g2.dispose();

                // Llamar a la implementación original para pintar el texto correctamente
                super.paintSafely(g);
            }

            @Override
            protected void paintBackground(Graphics g) {
                // No hacemos nada aquí para evitar conflictos
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void txtRfcRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfcRegistrarSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcRegistrarSalidaActionPerformed

    private void btnRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSalidaActionPerformed
        try {
            if (this.empleadoEncontrado == null) {
                JOptionPane.showMessageDialog(this, "Primero busque un empleado válido", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            boolean registroExitoso = control.registrarSalida(
                this.empleadoEncontrado,  
                LocalDate.now(),
                LocalTime.now()
            );
            
            if (registroExitoso) {
                JOptionPane.showMessageDialog(this, "Salida registrada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                resetearFormulario();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No se pudo registrar la salida. Verifique que el empleado haya registrado entrada hoy.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (PresentacionException ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar salida: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarSalidaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ControlFlujo.mostrarSubmenuRegistrarAsistenia();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        try {
            String rfc = txtRfcRegistrarSalida.getText().trim();

            if (rfc.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Favor de ingresar un rfc", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            EmpleadoDTO empleado = new EmpleadoDTO();
            empleado.setRfc(rfc);

            ControlAsistencia control = ControlAsistencia.getInstance();
            EmpleadoDTO empleadoEncontrado = control.buscarEmpleadoPorRFC(empleado);
            if(!control.validarHorarioLaboral(empleadoEncontrado, LocalDate.now())){
                JOptionPane.showMessageDialog(this, "Este empleado no tiene asignado este dia en su horario", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (empleadoEncontrado != null) {
                mostrarTodo();
                jlblNombreEmpleado.setText(empleadoEncontrado.getNombre()+" "+empleadoEncontrado.getApellidoPaterno()+" "+empleadoEncontrado.getApellidoMaterno());

                HorarioLaboralDTO horario = control.obtenerDetallesHorarioLaboralDia(
                    empleadoEncontrado, 
                    LocalDate.now()
                );
                
                jlblHoraDeSalidaEsperada.setText(horario.getHoraInicioTurno().format(DateTimeFormatter.ofPattern("HH:mm")));
    

                btnRegistrarSalida.setEnabled(true);
            } else {
                ocultarTodo();
                JOptionPane.showMessageDialog(this, "No se encontró empleado con ese RFC", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (PresentacionException e) {
            ocultarTodo();
            OptionPane.showErrorMessage(this, "ERROR: " + e.getMessage(), "Error de búsqueda");
        }  
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed
    
    
    private void mostrarTodo() {
        jLabel1.setVisible(true);
        jlblNombreEmpleado.setVisible(true);
        jLabel3.setVisible(true);
        jlblFechaActual.setVisible(true);
        jLabel4.setVisible(true);
        jlblHoraDeSalidaEsperada.setVisible(true);
        jLabel5.setVisible(true);
        jlblHoraDeSalida.setVisible(true);
        btnRegistrarSalida.setVisible(true);
        btnCancelar.setVisible(true);
        
        jlblFechaActual.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        jlblHoraDeSalida.setText(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
    }
    
    
    private void ocultarTodo() {
        jLabel1.setVisible(false);
        jlblNombreEmpleado.setVisible(false);
        jLabel3.setVisible(false);
        jlblFechaActual.setVisible(false);
        jLabel4.setVisible(false);
        jlblHoraDeSalidaEsperada.setVisible(false);
        jLabel5.setVisible(false);
        jlblHoraDeSalida.setVisible(false);
    }
    
    private void resetearFormulario() {
        this.empleadoEncontrado = null;
        txtRfcRegistrarSalida.setText("");
        ocultarTodo();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jlblFechaActual;
    private javax.swing.JLabel jlblHoraDeSalida;
    private javax.swing.JLabel jlblHoraDeSalidaEsperada;
    private javax.swing.JLabel jlblNombreEmpleado;
    private javax.swing.JTextField txtRfcRegistrarSalida;
    // End of variables declaration//GEN-END:variables
}
